name: 'AWS VPC Creation - Terraform Plan'

on:
  pull_request:
  push:
    branches:
      - main

env:
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_CLOUD_ORGANIZATION: "mudragiri"
  TF_CLOUD_WORKSPACE: "aws0_useast_1_vpc"
  CONFIG_DIRECTORY: "./"
  tfc_command: "destroy"

jobs:
  terraform:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt

      # Set up Terraform Cloud Authentication
      - name: Terraform Cloud Login
        run: |
          echo "Logging into Terraform Cloud"
          echo $HOME
          echo ${{ secrets.TF_API_TOKEN }}
          mkdir -p $HOME/.terraform.d
          echo "{\"credentials\":{\"app.terraform.io\":{\"token\":\"${{ secrets.TF_API_TOKEN }}\"}}}" > $HOME/.terraform.d/credentials.tfrc.json
          cat $HOME/.terraform.d/credentials.tfrc.json
          # terraform login 

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init #-backend-config="hostname=app.terraform.io" -backend-config="organization=${{ env.TF_CLOUD_ORGANIZATION}}" -backend-config="workspace=${{ env.TF_CLOUD_WORKSPACE}}"
      
      # Run Terraform plan using specific variable file
      - name: Terraform Apply
        run: terraform ${{ env.tfc_command}} -var-file=env_variables/aws0_useast_1.tfvars 
